Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  # Máquina maestro
  config.vm.define "FLASK-GUNICORN" do |pythonweb|
    pythonweb.vm.hostname = "www.deaw.test"
    pythonweb.vm.network "private_network", ip: "192.168.57.3"
    pythonweb.vm.provider "virtualbox" do |vb|
      vb.name = "FLASK-GUNICORN"
    end
    
    pythonweb.vm.provision "shell", inline: <<-SHELL
      echo "------------------- INSTALACIÓN DE PAQUETES -------------------"
      apt-get update -y
      apt-get install -y nginx python3-pip
      pip3 install pipenv
      pipenv --version
      pip3 install python-dotenv
      echo "------------------- INSTALACIÓN DE PAQUETES -------------------"

      echo "------------------- CONFIGURACIÓN DE NGINX, FLASK Y GUNICORN COMO ROOT -------------------"
      systemctl status nginx
      mkdir -p /var/www/app
      chown -R vagrant:www-data /var/www/app
      chmod -R 755 /var/www/app
      cp /vagrant/config/amz /etc/nginx/sites-available/default
      ln -s /etc/nginx/sites-available/amz /etc/nginx/sites-enabled/default
      systemctl restart nginx
      systemctl status nginx
      sudo cp -r /vagrant/config/flask/* /var/www/app
      cp /vagrant/config/flask/flask_app.service /etc/systemd/system
      echo "------------------- CONFIGURACIÓN DE NGINX, FLASK Y GUNICORN SERVICE COMO ROOT -------------------"
    SHELL

    pythonweb.vm.provision "shell", privileged: false, inline: <<-SHELL
      echo "------------------- INSTALACIÓN Y CONFIGURACIÓN DE FLASK Y GUNICORN -------------------"
      cd /var/www/app
      
      # Crear el entorno virtual con pipenv
      pipenv --python 3.9
      pipenv install flask gunicorn
      
      # Establecer variable de entorno para Flask
      echo 'export FLASK_APP=application.py' >> ~/.bashrc
      echo 'export FLASK_ENV=production' >> ~/.bashrc
      source ~/.bashrc

      # gunicorn --workers 4 --bind 0.0.0.0:8666 wsgi:app
      echo "------------------- INSTALACIÓN Y CONFIGURACIÓN DE FLASK Y GUNICORN -------------------"
    SHELL
  end
end
